# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Shared Library CI

on:
  push:
    branches: [main]
  pull_request:
# Intentionally left blank -- run on PRs against all branches.

jobs:
  shared-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create keys.ts
        run: |
          echo "/* eslint-disable max-len */ export const FIREBASE_API_KEY = ''; export const RECAPTCHA3_SITE_KEY = ''; export const PROD_FIREBASE_API_KEY = ''; export const PROD_RECAPTCHA3_SITE_KEY = '' /* eslint-enable max-len */" > projects/frontend/src/environments/keys.ts

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run shared:lint

      - name: Test
        run: npm run shared:test:headless

      - name: Build
        run: npm run shared:build:production
